# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medicsystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# 需要新加入的包
from CRUD.CRUD_logic import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from WindowsDesign.child_widget import *
from pathlib import Path
from CRUD.predict_show import *
import math

class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 861, 561))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 390, 211, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(390, 340, 91, 16))
        self.label.setObjectName("label")
        self.Input_24 = QtWidgets.QLineEdit(self.tab)
        self.Input_24.setGeometry(QtCore.QRect(490, 340, 261, 20))
        self.Input_24.setObjectName("Input_24")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(760, 340, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 350, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(11, 31, 18, 16))
        self.label_3.setObjectName("label_3")
        self.Input_1 = QtWidgets.QLineEdit(self.groupBox)
        self.Input_1.setGeometry(QtCore.QRect(77, 32, 105, 20))
        self.Input_1.setAcceptDrops(True)
        self.Input_1.setFrame(True)
        self.Input_1.setObjectName("Input_1")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 31, 92, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.Input_2 = QtWidgets.QLineEdit(self.groupBox)
        self.Input_2.setGeometry(QtCore.QRect(77, 60, 105, 20))
        self.Input_2.setObjectName("Input_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(11, 60, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(190, 60, 30, 16))
        self.label_5.setObjectName("label_5")
        self.Input_3 = QtWidgets.QLineEdit(self.groupBox)
        self.Input_3.setGeometry(QtCore.QRect(224, 60, 106, 20))
        self.Input_3.setObjectName("Input_3")
        self.Input_4 = QtWidgets.QLineEdit(self.groupBox)
        self.Input_4.setGeometry(QtCore.QRect(77, 86, 105, 20))
        self.Input_4.setObjectName("Input_4")
        self.label_51 = QtWidgets.QLabel(self.groupBox)
        self.label_51.setGeometry(QtCore.QRect(11, 86, 36, 16))
        self.label_51.setObjectName("label_51")
        self.Input_5 = QtWidgets.QLineEdit(self.groupBox)
        self.Input_5.setGeometry(QtCore.QRect(224, 86, 106, 20))
        self.Input_5.setObjectName("Input_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(190, 86, 30, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(11, 112, 24, 16))
        self.label_7.setObjectName("label_7")
        self.Input_6 = QtWidgets.QLineEdit(self.groupBox)
        self.Input_6.setGeometry(QtCore.QRect(77, 112, 105, 20))
        self.Input_6.setObjectName("Input_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 170, 350, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Input_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input_7.setGeometry(QtCore.QRect(83, 31, 48, 20))
        self.Input_7.setObjectName("Input_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(11, 31, 54, 16))
        self.label_8.setObjectName("label_8")
        self.Input_8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input_8.setGeometry(QtCore.QRect(292, 31, 48, 20))
        self.Input_8.setObjectName("Input_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(155, 31, 54, 16))
        self.label_9.setObjectName("label_9")
        self.Input_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input_9.setGeometry(QtCore.QRect(83, 57, 48, 20))
        self.Input_9.setObjectName("Input_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(11, 57, 66, 16))
        self.label_10.setObjectName("label_10")
        self.Input_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input_10.setGeometry(QtCore.QRect(292, 57, 48, 20))
        self.Input_10.setObjectName("Input_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(155, 57, 131, 16))
        self.label_11.setObjectName("label_11")
        self.Input_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input_11.setGeometry(QtCore.QRect(155, 83, 111, 20))
        self.Input_11.setObjectName("Input_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(11, 83, 138, 16))
        self.label_12.setObjectName("label_12")
        self.Input_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input_12.setGeometry(QtCore.QRect(155, 109, 111, 20))
        self.Input_12.setObjectName("Input_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(11, 109, 126, 16))
        self.label_13.setObjectName("label_13")
        self.Input_13 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input_13.setGeometry(QtCore.QRect(83, 135, 48, 20))
        self.Input_13.setObjectName("Input_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(11, 135, 42, 16))
        self.label_14.setObjectName("label_14")
        self.Input_14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.Input_14.setGeometry(QtCore.QRect(210, 135, 48, 20))
        self.Input_14.setObjectName("Input_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(155, 135, 42, 16))
        self.label_15.setObjectName("label_15")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 350, 350, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Input_17 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input_17.setGeometry(QtCore.QRect(300, 22, 43, 20))
        self.Input_17.setObjectName("Input_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(240, 22, 54, 16))
        self.label_18.setObjectName("label_18")
        self.Input_16 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input_16.setGeometry(QtCore.QRect(184, 22, 50, 20))
        self.Input_16.setObjectName("Input_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(118, 22, 54, 16))
        self.label_17.setObjectName("label_17")
        self.Input_15 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input_15.setGeometry(QtCore.QRect(72, 22, 40, 20))
        self.Input_15.setObjectName("Input_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(12, 22, 54, 16))
        self.label_16.setObjectName("label_16")
        self.Input_20 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input_20.setGeometry(QtCore.QRect(184, 48, 50, 20))
        self.Input_20.setObjectName("Input_20")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(12, 48, 54, 16))
        self.label_20.setObjectName("label_20")
        self.Input_18 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input_18.setGeometry(QtCore.QRect(97, 74, 77, 20))
        self.Input_18.setObjectName("Input_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(12, 74, 78, 16))
        self.label_19.setObjectName("label_19")
        self.Input_19 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input_19.setGeometry(QtCore.QRect(72, 48, 40, 20))
        self.Input_19.setObjectName("Input_19")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(118, 48, 54, 16))
        self.label_21.setObjectName("label_21")
        self.Input_22 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input_22.setGeometry(QtCore.QRect(264, 74, 78, 20))
        self.Input_22.setObjectName("Input_22")
        self.Input_21 = QtWidgets.QLineEdit(self.groupBox_3)
        self.Input_21.setGeometry(QtCore.QRect(300, 48, 43, 20))
        self.Input_21.setObjectName("Input_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(240, 48, 54, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(180, 74, 78, 16))
        self.label_23.setObjectName("label_23")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(410, 20, 411, 301))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        self.label_48.setGeometry(QtCore.QRect(20, 40, 371, 231))
        self.label_48.setText("")
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 480, 171, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.Input_23 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Input_23.setObjectName("Input_23")
        self.horizontalLayout.addWidget(self.Input_23)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(300, 30, 241, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 110, 400, 351))
        self.groupBox_11.setObjectName("groupBox_11")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_11)
        self.textBrowser_2.setEnabled(True)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 50, 330, 271))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setGeometry(QtCore.QRect(430, 110, 410, 351))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_53 = QtWidgets.QLabel(self.groupBox_12)
        self.label_53.setGeometry(QtCore.QRect(30, 60, 351, 241))
        self.label_53.setText("")
        self.label_53.setScaledContents(True)
        self.label_53.setObjectName("label_53")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(340, 480, 151, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(510, 370, 201, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setGeometry(QtCore.QRect(420, 310, 81, 16))
        self.label_47.setObjectName("label_47")
        self.MInput_24 = QtWidgets.QLineEdit(self.tab_3)
        self.MInput_24.setGeometry(QtCore.QRect(490, 310, 251, 20))
        self.MInput_24.setObjectName("MInput_24")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(754, 310, 71, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 20, 350, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.MInput_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.MInput_3.setGeometry(QtCore.QRect(253, 60, 77, 20))
        self.MInput_3.setObjectName("MInput_3")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(170, 60, 30, 16))
        self.label_36.setObjectName("label_36")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(21, 60, 60, 16))
        self.label_26.setObjectName("label_26")
        self.MInput_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.MInput_2.setGeometry(QtCore.QRect(87, 60, 77, 20))
        self.MInput_2.setObjectName("MInput_2")
        self.MInput_4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.MInput_4.setGeometry(QtCore.QRect(87, 86, 77, 20))
        self.MInput_4.setObjectName("MInput_4")
        self.label_52 = QtWidgets.QLabel(self.groupBox_5)
        self.label_52.setGeometry(QtCore.QRect(21, 86, 36, 16))
        self.label_52.setObjectName("label_52")
        self.MInput_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.MInput_5.setGeometry(QtCore.QRect(253, 86, 77, 20))
        self.MInput_5.setObjectName("MInput_5")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(170, 86, 30, 16))
        self.label_32.setObjectName("label_32")
        self.MInput_6 = QtWidgets.QLineEdit(self.groupBox_5)
        self.MInput_6.setGeometry(QtCore.QRect(87, 112, 77, 20))
        self.MInput_6.setObjectName("MInput_6")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(21, 112, 24, 16))
        self.label_35.setObjectName("label_35")
        self.label_44 = QtWidgets.QLabel(self.groupBox_5)
        self.label_44.setGeometry(QtCore.QRect(21, 31, 126, 16))
        self.label_44.setObjectName("label_44")
        self.MInput_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.MInput_1.setGeometry(QtCore.QRect(170, 32, 77, 20))
        self.MInput_1.setAcceptDrops(True)
        self.MInput_1.setFrame(True)
        self.MInput_1.setObjectName("MInput_1")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(253, 31, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 170, 350, 161))
        self.groupBox_6.setObjectName("groupBox_6")
        self.MInput_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.MInput_9.setGeometry(QtCore.QRect(83, 45, 40, 20))
        self.MInput_9.setObjectName("MInput_9")
        self.MInput_8 = QtWidgets.QLineEdit(self.groupBox_6)
        self.MInput_8.setGeometry(QtCore.QRect(290, 15, 40, 20))
        self.MInput_8.setObjectName("MInput_8")
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(11, 15, 54, 16))
        self.label_40.setObjectName("label_40")
        self.MInput_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.MInput_7.setGeometry(QtCore.QRect(83, 15, 40, 20))
        self.MInput_7.setObjectName("MInput_7")
        self.label_45 = QtWidgets.QLabel(self.groupBox_6)
        self.label_45.setGeometry(QtCore.QRect(11, 45, 66, 16))
        self.label_45.setObjectName("label_45")
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setGeometry(QtCore.QRect(155, 15, 54, 16))
        self.label_37.setObjectName("label_37")
        self.MInput_10 = QtWidgets.QLineEdit(self.groupBox_6)
        self.MInput_10.setGeometry(QtCore.QRect(290, 45, 40, 20))
        self.MInput_10.setObjectName("MInput_10")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(155, 45, 131, 16))
        self.label_25.setObjectName("label_25")
        self.MInput_11 = QtWidgets.QLineEdit(self.groupBox_6)
        self.MInput_11.setGeometry(QtCore.QRect(155, 75, 101, 20))
        self.MInput_11.setObjectName("MInput_11")
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(11, 75, 138, 16))
        self.label_38.setObjectName("label_38")
        self.MInput_12 = QtWidgets.QLineEdit(self.groupBox_6)
        self.MInput_12.setGeometry(QtCore.QRect(155, 105, 101, 20))
        self.MInput_12.setObjectName("MInput_12")
        self.label_31 = QtWidgets.QLabel(self.groupBox_6)
        self.label_31.setGeometry(QtCore.QRect(11, 105, 126, 16))
        self.label_31.setObjectName("label_31")
        self.MInput_14 = QtWidgets.QLineEdit(self.groupBox_6)
        self.MInput_14.setGeometry(QtCore.QRect(220, 135, 40, 20))
        self.MInput_14.setObjectName("MInput_14")
        self.label_43 = QtWidgets.QLabel(self.groupBox_6)
        self.label_43.setGeometry(QtCore.QRect(11, 135, 42, 16))
        self.label_43.setObjectName("label_43")
        self.label_46 = QtWidgets.QLabel(self.groupBox_6)
        self.label_46.setGeometry(QtCore.QRect(155, 135, 42, 16))
        self.label_46.setObjectName("label_46")
        self.MInput_13 = QtWidgets.QLineEdit(self.groupBox_6)
        self.MInput_13.setGeometry(QtCore.QRect(83, 135, 40, 20))
        self.MInput_13.setObjectName("MInput_13")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 340, 350, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget2.setGeometry(QtCore.QRect(21, 30, 329, 48))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 0, 0, 1, 1)
        self.MInput_15 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.MInput_15.setObjectName("MInput_15")
        self.gridLayout_2.addWidget(self.MInput_15, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 0, 2, 1, 1)
        self.MInput_16 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.MInput_16.setObjectName("MInput_16")
        self.gridLayout_2.addWidget(self.MInput_16, 0, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 0, 4, 1, 1)
        self.MInput_17 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.MInput_17.setObjectName("MInput_17")
        self.gridLayout_2.addWidget(self.MInput_17, 0, 5, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 1, 0, 1, 1)
        self.MInput_19 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.MInput_19.setObjectName("MInput_19")
        self.gridLayout_2.addWidget(self.MInput_19, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 1, 2, 1, 1)
        self.MInput_20 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.MInput_20.setObjectName("MInput_20")
        self.gridLayout_2.addWidget(self.MInput_20, 1, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 4, 1, 1)
        self.MInput_21 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.MInput_21.setObjectName("MInput_21")
        self.gridLayout_2.addWidget(self.MInput_21, 1, 5, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget3.setGeometry(QtCore.QRect(21, 80, 321, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30)
        self.MInput_18 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.MInput_18.setObjectName("MInput_18")
        self.horizontalLayout_2.addWidget(self.MInput_18)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_2.addWidget(self.label_39)
        self.MInput_22 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.MInput_22.setObjectName("MInput_22")
        self.horizontalLayout_2.addWidget(self.MInput_22)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(420, 20, 411, 281))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_49 = QtWidgets.QLabel(self.groupBox_8)
        self.label_49.setGeometry(QtCore.QRect(20, 30, 370, 230))
        self.label_49.setText("")
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(110, 470, 191, 24))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_3.addWidget(self.label_28)
        self.MInput_23 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.MInput_23.setObjectName("MInput_23")
        self.horizontalLayout_3.addWidget(self.MInput_23)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(440, 90, 410, 351))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_50 = QtWidgets.QLabel(self.groupBox_9)
        self.label_50.setGeometry(QtCore.QRect(30, 60, 351, 241))
        self.label_50.setText("")
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 90, 400, 351))
        self.groupBox_10.setObjectName("groupBox_10")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_10)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(30, 50, 330, 271))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(320, 30, 216, 51))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_13.setGeometry(QtCore.QRect(40, 140, 401, 291))
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_54 = QtWidgets.QLabel(self.groupBox_13)
        self.label_54.setGeometry(QtCore.QRect(50, 30, 301, 241))
        self.label_54.setText("")
        self.label_54.setScaledContents(True)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_5)
        self.label_55.setGeometry(QtCore.QRect(50, 110, 54, 12))
        self.label_55.setObjectName("label_55")
        self.radioButton = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton.setGeometry(QtCore.QRect(50, 70, 111, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_2.setGeometry(QtCore.QRect(310, 70, 101, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_56 = QtWidgets.QLabel(self.tab_5)
        self.label_56.setGeometry(QtCore.QRect(130, 480, 101, 41))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_5)
        self.label_57.setEnabled(True)
        self.label_57.setGeometry(QtCore.QRect(240, 480, 51, 41))
        self.label_57.setObjectName("label_57")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(310, 110, 91, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_58 = QtWidgets.QLabel(self.tab_5)
        self.label_58.setGeometry(QtCore.QRect(160, 20, 121, 31))
        self.label_58.setObjectName("label_58")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 110, 91, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 440, 171, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_59 = QtWidgets.QLabel(self.tab_5)
        self.label_59.setGeometry(QtCore.QRect(570, 110, 54, 12))
        self.label_59.setObjectName("label_59")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_12.setGeometry(QtCore.QRect(210, 110, 51, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 914, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)

        # 修改加入的代码
        # ---
        self.textBrowser.setVisible(False)
        self.label_59.setVisible(False)
        self.textBrowser_2.setVisible(False)
        self.pushButton_6.setEnabled(False)
        self.pushButton_7.setEnabled(False)
        self.pushButton_4.setEnabled(False)
        self.pushButton_2.setEnabled(False)
        self.pushButton.setEnabled(False)
        self.pushButton_8.setEnabled(False)
        self.pushButton_9.setEnabled(False)
        self.pushButton_5.setEnabled(False)
        self.pushButton_3.setEnabled(False)
        self.label_57.setVisible(False)
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)
        self.pushButton_12.setEnabled(False)
        # ---end

        # 加入信号与槽的联系
        self.pushButton_6.clicked.connect(self.Isexist)
        self.pushButton_7.clicked.connect(self.add_img_path)
        self.action.triggered.connect(self.show_child)
        self.pushButton.clicked.connect(self.CheckInformation)
        self.pushButton_8.clicked.connect(self.add_img_path2)
        self.pushButton_4.clicked.connect(self.addPatience)  # 增
        self.pushButton_2.clicked.connect(self.before_delpatience)  # 删前查询
        self.pushButton_9.clicked.connect(self.delpatience)  # 删
        self.pushButton_3.clicked.connect(self.serchpatience)  # 查
        self.pushButton_5.clicked.connect(self.modifypatience)  # 改
        self.radioButton.toggled.connect(self.IsIdPredict)  # ID导出图片的预测
        self.radioButton_2.toggled.connect(self.IsPicPredict)    # 直接导入图片预测
        self.pushButton_10.clicked.connect(self.set_predict_image)  # 诊断预测中，采用新增图像模式，添加图像
        self.pushButton_11.clicked.connect(self.predict)
        self.pushButton_12.clicked.connect(self.check_id_img)
        # ---end

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Input_1, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.Input_2)
        MainWindow.setTabOrder(self.Input_2, self.Input_3)
        MainWindow.setTabOrder(self.Input_3, self.Input_4)
        MainWindow.setTabOrder(self.Input_4, self.Input_5)
        MainWindow.setTabOrder(self.Input_5, self.Input_6)
        MainWindow.setTabOrder(self.Input_6, self.Input_7)
        MainWindow.setTabOrder(self.Input_7, self.Input_8)
        MainWindow.setTabOrder(self.Input_8, self.Input_9)
        MainWindow.setTabOrder(self.Input_9, self.Input_10)
        MainWindow.setTabOrder(self.Input_10, self.Input_11)
        MainWindow.setTabOrder(self.Input_11, self.Input_12)
        MainWindow.setTabOrder(self.Input_12, self.Input_13)
        MainWindow.setTabOrder(self.Input_13, self.Input_14)
        MainWindow.setTabOrder(self.Input_14, self.Input_15)
        MainWindow.setTabOrder(self.Input_15, self.Input_16)
        MainWindow.setTabOrder(self.Input_16, self.Input_17)
        MainWindow.setTabOrder(self.Input_17, self.Input_18)
        MainWindow.setTabOrder(self.Input_18, self.Input_19)
        MainWindow.setTabOrder(self.Input_19, self.Input_20)
        MainWindow.setTabOrder(self.Input_20, self.Input_21)
        MainWindow.setTabOrder(self.Input_21, self.Input_22)
        MainWindow.setTabOrder(self.Input_22, self.Input_23)
        MainWindow.setTabOrder(self.Input_23, self.Input_24)
        MainWindow.setTabOrder(self.Input_24, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.MInput_1)
        MainWindow.setTabOrder(self.MInput_1, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.MInput_2)
        MainWindow.setTabOrder(self.MInput_2, self.MInput_3)
        MainWindow.setTabOrder(self.MInput_3, self.MInput_4)
        MainWindow.setTabOrder(self.MInput_4, self.MInput_5)
        MainWindow.setTabOrder(self.MInput_5, self.MInput_6)
        MainWindow.setTabOrder(self.MInput_6, self.MInput_7)
        MainWindow.setTabOrder(self.MInput_7, self.MInput_8)
        MainWindow.setTabOrder(self.MInput_8, self.MInput_9)
        MainWindow.setTabOrder(self.MInput_9, self.MInput_10)
        MainWindow.setTabOrder(self.MInput_10, self.MInput_11)
        MainWindow.setTabOrder(self.MInput_11, self.MInput_12)
        MainWindow.setTabOrder(self.MInput_12, self.MInput_13)
        MainWindow.setTabOrder(self.MInput_13, self.MInput_14)
        MainWindow.setTabOrder(self.MInput_14, self.MInput_15)
        MainWindow.setTabOrder(self.MInput_15, self.MInput_16)
        MainWindow.setTabOrder(self.MInput_16, self.MInput_17)
        MainWindow.setTabOrder(self.MInput_17, self.MInput_18)
        MainWindow.setTabOrder(self.MInput_18, self.MInput_19)
        MainWindow.setTabOrder(self.MInput_19, self.MInput_20)
        MainWindow.setTabOrder(self.MInput_20, self.MInput_21)
        MainWindow.setTabOrder(self.MInput_21, self.MInput_22)
        MainWindow.setTabOrder(self.MInput_22, self.MInput_23)
        MainWindow.setTabOrder(self.MInput_23, self.MInput_24)
        MainWindow.setTabOrder(self.MInput_24, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "确认录入"))
        self.label.setText(_translate("MainWindow", "录入图像的路径："))
        self.pushButton_7.setText(_translate("MainWindow", "添加图像"))
        self.groupBox.setTitle(_translate("MainWindow", "患者信息"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">ID：</p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "查询ID是否存在"))
        self.label_4.setText(_translate("MainWindow", "住院日期："))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">性别：</p></body></html>"))
        self.label_51.setText(_translate("MainWindow", "年龄："))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">身高：</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">BMI：</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "临床信息"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">糖料病史：</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">高血压史：</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">肾病家族史：</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:8pt;\">肾穿前是否服用ACEI/ARB：</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">肾穿前蛋白尿病史(月数)：</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">持续镜下血尿史(月数)：</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">收缩压：</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">舒张压：</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "影像信息"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">右肾高度：</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">右肾宽度：</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">右肾长度：</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">左肾长度：</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">右肾皮质厚度：</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">左肾宽度：</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">左肾高度：</p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">左肾皮质厚度：</p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "图片显示"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">诊断结果:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "录入病人数据"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">病人ID：</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "查询信息"))
        self.groupBox_11.setTitle(_translate("MainWindow", "信息显示"))
        self.groupBox_12.setTitle(_translate("MainWindow", "图像显示"))
        self.pushButton_9.setText(_translate("MainWindow", "确认删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "删除病人数据"))
        self.pushButton_5.setText(_translate("MainWindow", "确认修改"))
        self.label_47.setText(_translate("MainWindow", "新图像路径："))
        self.pushButton_8.setText(_translate("MainWindow", "添加图像"))
        self.groupBox_5.setTitle(_translate("MainWindow", "患者信息"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">性别：</p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "住院日期："))
        self.label_52.setText(_translate("MainWindow", "年龄："))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">身高：</p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">BMI：</p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">输入需要修改信息的ID:</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "查询信息"))
        self.groupBox_6.setTitle(_translate("MainWindow", "临床信息"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">糖料病史：</p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">肾病家族史：</p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">高血压史：</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:8pt;\">肾穿前是否服用ACEI/ARB：</span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">肾穿前蛋白尿病史(月数)：</p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">持续镜下血尿史(月数)：</p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">收缩压：</p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">舒张压：</p></body></html>"))
        self.groupBox_7.setTitle(_translate("MainWindow", "影像信息"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">右肾长度：</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">右肾宽度：</p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">右肾高度：</p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">左肾长度：</p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">左肾宽度：</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">左肾高度：</p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">右肾皮质厚度：</p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">左肾皮质厚度：</p></body></html>"))
        self.groupBox_8.setTitle(_translate("MainWindow", "图片显示"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">诊断结果：</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "修改病人数据"))
        self.groupBox_9.setTitle(_translate("MainWindow", "图像显示"))
        self.groupBox_10.setTitle(_translate("MainWindow", "信息显示"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">病人ID：</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "查询信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "查询病人数据"))
        self.groupBox_13.setTitle(_translate("MainWindow", "显示图像"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p>输入ID：</p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "本地患者ID诊断"))
        self.radioButton_2.setText(_translate("MainWindow", "新增图像诊断"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">诊断结果：</span></p></body></html>"))
        self.label_57.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">1</span></p></body></html>"))
        self.pushButton_10.setText(_translate("MainWindow", "添加图像"))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">模式选择：</span></p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "诊断预测"))
        self.label_59.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_12.setText(_translate("MainWindow", "ID查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "患者诊断预测"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.action.setText(_translate("MainWindow", "路径设置"))

# 需要新加入的函数
    def Is_exist(self, id_input):
        flag = 0
        if id_input == '':
            QMessageBox.warning(self, '警告', '请输入ID后再点击查询', QMessageBox.Yes)
        elif id_input.isdecimal():
            if 0 < int(id_input) < 9999999:
                for key, value in patience_dict.items():
                    if id_input == value:
                        flag = 1
                        break
                if flag == 1:
                    QMessageBox.about(self, 'message', 'ID合理。')
                    return 1
                else:
                    QMessageBox.warning(self, '警告', '该ID不存在，请重新输入ID！', QMessageBox.Yes)
        else:
            QMessageBox.critical(self, 'error', '输入错误，请重新输入！', QMessageBox.Yes)
        return 0

    def Isexist(self):
        self.pushButton_4.setEnabled(False)
        flag = 0
        if self.Input_1.text() == '':
            QMessageBox.warning(self, '警告', '请输入ID后再点击查询', QMessageBox.Yes)
        elif self.Input_1.text().isdecimal():
            if 0 < int(self.Input_1.text()) < 9999999:
                for key, value in patience_dict.items():
                    if str(self.Input_1.text()) == value:
                        flag = 1
                        break
                if flag == 1:
                    QMessageBox.warning(self, '警告', '该ID已存在，请重新输入ID！', QMessageBox.Yes)
                else:
                    QMessageBox.about(self, 'message', 'ID合理。')
                    self.pushButton_4.setEnabled(True)
                    return False
        else:
            QMessageBox.critical(self, 'error', '输入错误，请重新输入！', QMessageBox.Yes)
        return True

    def Isexist2(self):
        flag = 0
        self.pushButton_8.setEnabled(False)
        self.pushButton_5.setEnabled(False)
        if self.MInput_1.text() == '':
            QMessageBox.warning(self, '警告', '请输入ID后再点击查询', QMessageBox.Yes)
        elif self.MInput_1.text().isdecimal():
            if 0 < int(self.MInput_1.text()) < 9999999:
                for key, value in patience_dict.items():
                    if str(self.MInput_1.text()) == value:
                        flag = 1
                        break
                if flag == 1:
                    self.pushButton_8.setEnabled(True)
                    self.pushButton_5.setEnabled(True)
                    return True
                else:
                    QMessageBox.warning(self, '警告', '该ID不存在，请重新输入ID！', QMessageBox.Yes)
        else:
            QMessageBox.critical(self, 'error', '输入错误，请重新输入！', QMessageBox.Yes)
        return False

    def add_img_path(self):
        img_path, _ = QFileDialog.getOpenFileName(self, '打开文件', '.', '图像文件 (*.jpg *.png)')
        self.Input_24.setText(img_path)
        img_file = Path(img_path)
        if img_file.is_file():
            self.label_48.setPixmap(QPixmap(img_path))
        else:
            self.label_48.clear()
        #     QMessageBox.warning(self, '警告', '图像路径输入有误！', QMessageBox.Yes)

    def add_img_path2(self):
        img_path, _ = QFileDialog.getOpenFileName(self, '打开文件', '.', '图像文件 (*.jpg *.png)')
        self.MInput_24.setText(img_path)
        img_file = Path(img_path)
        if img_file.is_file():
            self.label_49.setPixmap(QPixmap(img_path))
        else:
            self.label_49.clear()
        #    QMessageBox.warning(self, '警告', '图像路径输入有误！', QMessageBox.Yes)

    def show_image(self, img_path, showed_object):
        img_File = Path(img_path)
        if img_File.is_file():
            showed_object.setPixmap(QPixmap(img_path))
        else:
            # QMessageBox.warning(self, '警告', '图像路径输入有误！', QMessageBox.Yes)
            pass

    def addPatience(self):
        if str(self.Input_1.text()) not in patience_list:
            list1 = []
            for i in range(1, self.Msystem.cols + 1):
                content = eval('self.Input_' + str(i)).text()
                list1.append(str(content))
            check_list = list1[:]
            check_list.remove(check_list[0])
            check_result = self.Msystem.check_data(check_list)
            if check_result == 0:
                list1.insert(1, '')
                self.Msystem.add_patience(list1)
                # 录入图像信息
                new_img_path = self.Input_24.text()
                is_ill = self.Input_23.text()
                print(new_img_path, '11111')
                img_file = Path(new_img_path)
                if img_file.is_file():
                    full_id = self.fill_ID(int(list1[0]))
                    self.Msystem.save_picture(new_img_path, full_id + '-rk', str(is_ill))
                elif new_img_path == '':
                    pass
                else:
                    QMessageBox.warning(self, '警告', '图片路径出错，请重新输入！')
            else:
                QMessageBox.warning(self, '警告', check_result)
        else:
            QMessageBox.warning(self, '警告', 'ID已存在，请勿重复添加！')

    def before_delpatience(self):
        self.textBrowser_2.setVisible(False)
        patience_id = self.lineEdit.text()
        flag = 0
        if patience_id == '':
            QMessageBox.warning(self, '警告', '请输入ID！', QMessageBox.Yes)
        elif patience_id.isdecimal():
            if 0 < int(patience_id) < 9999999:
                for key, value in patience_dict.items():
                    if patience_id == value:
                        flag = 1
                        break
                if flag == 1:
                    list1 = self.Msystem.search_patience(patience_id)
                    self.textBrowser_2.setText(f"患者信息：\n"
                                               f"ID：{list1[0]}\t住院日期：{list1[2]}\t性别：{list1[3]}\t"
                                               f"年龄：{list1[4]}\t身高：{list1[5]}\tBMI：{list1[6]}\n\n"
                                               f"临床信息：\n"
                                               f"糖料病史：{list1[7]}\t高血压史：{list1[8]}\t肾病家族史：{list1[9]}\n"
                                               f"肾穿前是否服用ACBI/ARB：{list1[10]}\n肾穿前蛋白尿病史(月数)：{list1[11]}\n"
                                               f"持续镜下血尿史(月数)：{list1[12]}\n收缩压：{list1[13]}\t舒张压：{list1[14]}\n\n"
                                               f"影像信息：\n"
                                               f"右肾长度：{list1[15]}\t右肾宽度：{list1[16]}\n右肾高度：{list1[17]}\t"
                                               f"右肾皮质厚度：{list1[18]}\n左肾长度：{list1[19]}\t左肾宽度：{list1[20]}\n"
                                               f"左肾高度：{list1[21]}\t左肾皮质厚度：{list1[22]}")
                    self.textBrowser_2.setVisible(True)
                    # 查询图像
                    full_id = self.fill_ID(int(list1[0]))
                    if self.Msystem.search_picture(full_id, list1[23]) == 1:
                        if list1[23] == 'None':
                            img_path = self.Msystem.Local_Path + '/no_design' + '/' + full_id + '-rk.jpg'
                        else:
                            img_path = self.Msystem.Local_Path + '/M' + list1[23] + '/' + full_id + '-rk.jpg'
                        print('图像路径是：', img_path)
                        img_file = Path(img_path)
                        if img_file.is_file():
                            self.show_image(img_path, self.label_53)
                    QMessageBox.information(self, 'Message', '查询成功！', QMessageBox.Yes)
                    self.pushButton_9.setEnabled(True)
                else:
                    QMessageBox.warning(self, '警告', '查无此人！')
            else:
                QMessageBox.warning(self, '警告', '输入ID越界，请重新输入！')
        else:
            QMessageBox.critical(self, 'error', '输入错误，请重新输入！', QMessageBox.Yes)

    def delpatience(self):
        patience_id = self.lineEdit.text()
        flag = 0
        if patience_id == '':
            QMessageBox.warning(self, '警告', '请输入ID后再点击删除！', QMessageBox.Yes)
        elif patience_id.isdecimal():
            if 0 < int(patience_id) < 9999999:
                for key, value in patience_dict.items():
                    if patience_id == value:
                        flag = 1
                        break
                if flag == 1:
                    full_id = self.fill_ID(int(patience_id))
                    lista = self.Msystem.search_patience(patience_id)
                    is_ill = lista[23]
                    print(lista)
                    print(is_ill)
                    self.Msystem.del_picture(full_id, is_ill)
                    self.Msystem.del_patience(patience_id)
                    self.textBrowser_2.clear()
                    self.textBrowser_2.setVisible(False)
                    self.label_53.clear()
                    print('图像和数据均已删除')
                    self.Msystem.init_patience_list()
                    print('ID对应列表已刷新')
                    QMessageBox.information(self, 'Message', '删除成功！', QMessageBox.Yes)
                else:
                    QMessageBox.warning(self, '警告', '查无此人，无法完成删除！')
            else:
                QMessageBox.warning(self, '警告', '输入ID越界，请重新输入！')
        else:
            QMessageBox.critical(self, 'error', '输入错误，请重新输入！', QMessageBox.Yes)

    def serchpatience(self):
        self.label_50.clear()
        list1 = []
        patience_id = self.lineEdit_2.text()
        flag = 0
        if patience_id == '':
            QMessageBox.warning(self, '警告', '请输入ID后再点击查询！', QMessageBox.Yes)
        elif patience_id.isdecimal():
            if 0 < int(patience_id) < 9999999:
                for key, value in patience_dict.items():
                    if patience_id == value:
                        flag = 1
                        break
                if flag == 1:
                    list1 = self.Msystem.search_patience(patience_id)
                    del list1[1]
                    self.textBrowser.setText(f"患者信息：\n"
                                             f"ID：{list1[0]}\t住院日期：{list1[1]}\t性别：{list1[2]}\t"
                                             f"年龄：{list1[3]}\t身高：{list1[4]}\tBMI：{list1[5]}\n\n"
                                             f"临床信息：\n"
                                             f"糖料病史：{list1[6]}\t高血压史：{list1[7]}\t肾病家族史：{list1[8]}\n"
                                             f"肾穿前是否服用ACBI/ARB：{list1[9]}\n肾穿前蛋白尿病史(月数)：{list1[10]}\n"
                                             f"持续镜下血尿史(月数)：{list1[11]}\n收缩压：{list1[12]}\t舒张压：{list1[13]}\n\n"
                                             f"影像信息：\n"
                                             f"右肾长度：{list1[14]}\t右肾宽度：{list1[15]}\n右肾高度：{list1[16]}\t"
                                             f"右肾皮质厚度：{list1[17]}\n左肾长度：{list1[18]}\t左肾宽度：{list1[19]}\n"
                                             f"左肾高度：{list1[20]}\t左肾皮质厚度：{list1[21]}")
                    self.textBrowser.setVisible(True)
                    # 查询图像
                    full_id = self.fill_ID(int(list1[0]))
                    if list1[22] != 'None':
                        img_path = self.Msystem.Local_Path + '/M' + list1[22] + '/' + full_id + '-rk.jpg'
                    else:
                        img_path = self.Msystem.Local_Path + '/no_design' + '/' + full_id + '-rk.jpg'
                    print(img_path)
                    img_file = Path(img_path)
                    if img_file.is_file():
                        self.show_image(img_path, self.label_50)
                    QMessageBox.information(self, 'Message', '查询成功！', QMessageBox.Yes)
                else:
                    QMessageBox.warning(self, '警告', '查无此人!')
                    self.textBrowser.setVisible(False)
        else:
            QMessageBox.critical(self, 'error', '输入错误，请重新输入！', QMessageBox.Yes)

    def show_child(self):
        self.child_window = Ui_Form()
        self.child_window.setupUi(self.child_window)
        self.child_window.my_Signal.connect(self.refresh_path)
        self.child_window.show()

    # 关闭子窗口时，生成医疗系统的对象实例--------begin
    def refresh_path(self):
        Excel_Path = self.child_window.excel_path
        Local_Path = self.child_window.local_path
        excel_file = Path(Excel_Path)
        if excel_file.is_file():
            self.Msystem = PatienceManager(Local_Path, '', Excel_Path)
            self.pushButton_6.setEnabled(True)
            self.pushButton_7.setEnabled(True)
            self.pushButton_2.setEnabled(True)
            self.pushButton.setEnabled(True)
            self.pushButton_3.setEnabled(True)
            self.pushButton_11.setEnabled(True)
    #-------------------------------------------end

    def modifypatience(self):
        list2 = []
        print(self.Msystem.cols)
        for i in range(1, self.Msystem.cols):
            content = eval('self.MInput_' + str(i)).text()
            list2.append(content)
        check_list = list2[:]
        check_list.remove(check_list[0])
        check_result = self.Msystem.check_data(check_list)
        if check_result == 0:
            list2.insert(1, 'None')
            print(list2)
            self.Msystem.modify_patience(list2)
            # 录入图像信息
            new_img_path = self.MInput_24.text()
            is_ill = self.MInput_23.text()
            img_file = Path(new_img_path)
            if img_file.is_file():
                full_id = self.fill_ID(int(list2[0]))
                self.Msystem.del_picture(full_id, is_ill)
                self.Msystem.save_picture(new_img_path, full_id + '-rk', str(is_ill))
            QMessageBox.about(self, '关于', '修改成功！')
        else:
            QMessageBox.warning(self, '警告', check_result)


    def CheckInformation(self):
        if self.Isexist2():
            pid = self.MInput_1.text()
            patience_information_list = self.Msystem.search_patience(pid)
            del patience_information_list[1]
            if patience_information_list[1] != 'None':
                patience_information_list[1] = patience_information_list[1][0:10]
            for i in range(2, len(patience_information_list)+1):
                eval('self.MInput_' + str(i)).setText(patience_information_list[i-1])
        else:
            for i in range(2, 24):
                eval('self.MInput_' + str(i)).clear()



    def fill_ID(self, iID):
        for i in range(8):
            if pow(10, i) <= iID < pow(10, i+1):
                str1 = '0'*(8-i) + str(iID)
                return str1
        return str(iID)

    def IsIdPredict(self):
        if self.radioButton.isChecked():
            self.lineEdit_3.setEnabled(True)
            self.pushButton_12.setEnabled(True)
            self.label_54.clear()
        else:
            self.lineEdit_3.setEnabled(False)
            self.pushButton_12.setEnabled(False)

    def IsPicPredict(self):
        if self.radioButton_2.isChecked():
            self.pushButton_10.setEnabled(True)
            self.label_54.clear()
        else:
            self.pushButton_10.setEnabled(False)

    def check_id_img(self):
        self.label_54.clear()
        self.label_57.setVisible(False)
        pid = self.lineEdit_3.text()
        if self.Is_exist(pid) == 1:
            full_id = self.fill_ID(int(pid))
            list1 = self.Msystem.search_patience(pid)
            print(len(list1), list1)
            if list1[23] == '0' or list1[23] == '1':
                img_path = self.Msystem.Local_Path + '/M' + list1[23] + '/' + full_id + '-rk.jpg'
            else:
                img_path = self.Msystem.Local_Path + '/no_design' + '/' + full_id + '-rk.jpg'
            print(img_path)
            self.show_image(img_path, self.label_54)

    def set_predict_image(self):
        self.label_57.setVisible(False)
        img_path, _ = QFileDialog.getOpenFileName(self, '打开文件', '.', '图像文件 (*.jpg *.png)')
        self.show_image(img_path, self.label_54)
        self.label_59.setText(img_path)


    def predict(self):
        if self.radioButton.isChecked():
            pid = self.lineEdit_3.text()
            if pid != '':
                list1 = self.Msystem.search_patience(pid)
                full_id = self.fill_ID(int(pid))
                img_path = ''
                if list1[23] == '0' or list1[23] == '1':
                    QMessageBox.about(self, '关于', '该id已经有诊断结果，此次预测仅供参考！')
                    img_path = self.Msystem.Local_Path + '/M' + list1[23] + '/' + full_id + '-rk.jpg'
                elif list1[23] == 'None':
                    img_path = self.Msystem.Local_Path + '/no_design' + '/' + full_id + '-rk.jpg'
                img_file = Path(img_path)
                if img_file.is_file():
                    result = predict(resnet50_pth(num_classes, 'res_sgd_pre.pth').to(device), img_path)
                    if result == 'M1':
                        self.label_57.setText('1')
                    else:
                        self.label_57.setText('0')
                    self.label_57.setVisible(True)
        if self.radioButton_2.isChecked():
            img_path2 = self.label_59.text()
            img_file2 = Path(img_path2)
            if img_file2.is_file():
                result = predict(resnet50_pth(num_classes, 'res_sgd_pre.pth').to(device), img_path2)
                if result == 'M1':
                    self.label_57.setText('1')
                else:
                    self.label_57.setText('0')
                self.label_57.setVisible(True)
            pass